# Generated by Django 5.2 on 2025-07-14 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursepagedetails',
            name='title',
            field=models.CharField(choices=[('ai_advanced_digital_marketing', 'AI Advanced Digital Marketing'), ('graphic_design', 'Graphic Design'), ('ui/ux_design', 'UI/UX Design'), ('web_and_app_development', 'WEB & APP Development'), ('video_editing', 'Video Editing'), ('robotics', 'Robotics')], max_length=255),
        ),
        migrations.AlterField(
            model_name='sectionimages',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero'), ('leading_solution', 'Leading Solution'), ('transform_passion', 'Transform Passion'), ('discuss_together', 'Discuss Together'), ('thumbnail', 'Thumbnail'), ('about_us', 'About Us'), ('why_us', 'Why Us'), ('mission', 'Mission'), ('confirm_career', 'Confirm Career'), ('contact', 'Contact')], max_length=255),
        ),
        migrations.CreateModel(
            name='CourseSinglePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('main_image', models.ImageField(default=None, upload_to='images/')),
                ('second_image', models.ImageField(default=None, upload_to='images/')),
                ('third_image', models.ImageField(default=None, upload_to='images/')),
                ('points', models.TextField()),
                ('keyPoints', models.TextField()),
                ('specialties', models.TextField()),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.course')),
            ],
        ),
    ]
