# Generated by Django 5.2 on 2025-07-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_profile_is_public_alter_coursepagedetails_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(choices=[('ai_advanced_digital_marketing', 'AI Advanced Digital Marketing'), ('graphic_design', 'Graphic Design'), ('ui/ux_design', 'UI/UX Design'), ('web_and_app_development', 'WEB & APP Development'), ('video_editing', 'Video Editing'), ('robotics', 'Robotics')], max_length=255),
        ),
    ]
