# Generated by Django 5.2 on 2025-07-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_alter_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_access_profile',
            field=models.BooleanField(default=False),
        ),
    ]
