# Generated by Django 5.2 on 2025-08-26 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_profile_can_access_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('fee_paid', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.course')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.profile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('attended', models.BooleanField(default=False)),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Application.studentcourse')),
            ],
        ),
    ]
