# Generated by Django 5.2 on 2025-08-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0008_studentcourse_studentattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
