# Generated by Django 5.2 on 2025-08-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0009_studentcourse_paid_amount_studentcourse_paid_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourse',
            old_name='fee_paid',
            new_name='payment_completed',
        ),
    ]
