# Generated by Django 5.2 on 2025-08-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0010_rename_fee_paid_studentcourse_payment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='class_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='attended_at',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
    ]
