# Generated by Django 5.2 on 2025-08-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0011_studentattendance_class_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='bach_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
