# Generated by Django 5.2 on 2025-08-30 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0015_alter_profile_course_alter_studentattendance_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='student_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Application.course'),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='attended_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StudentCourse',
        ),
    ]
