# Generated by Django 5.0 on 2025-09-09 08:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0016_alter_studentattendance_student_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, help_text="E.g. '6 months' or '40 hours'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course price in INR (or your currency)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.CharField(blank=True, help_text='Name of the tutor/instructor', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(help_text='Detailed description of the course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sub_title',
            field=models.CharField(blank=True, help_text='Optional short subtitle for the course', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(choices=[('ai_advanced_digital_marketing', 'AI Advanced Digital Marketing'), ('graphic_design', 'Graphic Design'), ('ui_ux_design', 'UI/UX Design'), ('web_and_app_development', 'Web & App Development'), ('video_editing', 'Video Editing'), ('robotics', 'Robotics')], db_index=True, max_length=255),
        ),
    ]
