# Generated by Django 5.0 on 2025-09-11 14:06

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0017_alter_course_options_course_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='certificate',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
