# Generated by Django 5.0 on 2025-09-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0018_certificate_certificate_number_certificate_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LOGIN', 'New Login'), ('PROFILE', 'Profile Access Request'), ('ENQUIRY', 'Course Enquiry'), ('ADMISSION', 'Admission Form Submission')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_model', models.CharField(blank=True, max_length=50, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
