# Generated by Django 5.0 on 2025-09-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0020_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
