# Generated by Django 5.0 on 2025-09-16 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0023_remove_batches_time_end_batches_batch_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
