# Generated by Django 5.0 on 2025-09-16 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0024_alter_profile_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batches',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta, null=True),
        ),
    ]
