# Generated by Django 5.0 on 2025-09-16 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0025_alter_batches_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batches',
            name='batch_start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
    ]
