# Generated by Django 5.0 on 2025-09-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0026_alter_batches_batch_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batches',
            name='batch_start_date',
        ),
        migrations.RemoveField(
            model_name='batches',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='start_date',
        ),
        migrations.AddField(
            model_name='batches',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.CharField(blank=True, help_text='Name of the tutor/instructor', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bach_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
