# Generated by Django 5.0 on 2025-09-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0027_remove_batches_batch_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batches',
            name='time_end',
        ),
        migrations.AddField(
            model_name='batches',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
