# Generated by Django 5.0 on 2025-09-16 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0029_course_is_active_alter_course_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bach_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Application.batches'),
        ),
    ]
