# Generated by Django 5.0 on 2025-09-26 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0031_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Overall student progress in percentage (0–100)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('LOGIN', 'New Login'), ('PROFILE', 'Profile Access Request'), ('ENQUIRY', 'Course Enquiry'), ('ADMISSION', 'Admission Form Submission'), ('SESSION', 'New Session')], max_length=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_sessions', to='Application.tutorname'),
        ),
    ]
