# Generated by Django 5.0 on 2025-09-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0032_profile_progress_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorname',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tutors/'),
        ),
    ]
