# Generated by Django 5.0 on 2025-09-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0033_tutorname_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
