# Generated by Django 5.0 on 2025-09-30 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0036_alter_studentattendance_status_studentworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='Application.session'),
        ),
    ]
