# Generated by Django 5.0 on 2025-10-03 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0037_studentattendance_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batches',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='batches',
            name='tutor',
        ),
    ]
