# Generated by Django 5.0 on 2025-10-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0038_remove_batches_duration_remove_batches_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='batches',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
