# Generated by Django 5.0 on 2025-10-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0039_batches_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='marked_by_student',
            field=models.BooleanField(default=False),
        ),
    ]
