# Generated by Django 5.0 on 2025-10-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0040_studentattendance_marked_by_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='attended_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
