# Generated by Django 5.0 on 2025-11-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0041_alter_studentattendance_attended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Student Course price in INR (or your currency)', max_digits=10, null=True),
        ),
    ]
