# Generated by Django 5.0 on 2025-11-10 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0043_studentregion_profile_student_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='batches',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='batches',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.studentregion'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.studentregion'),
        ),
        migrations.AddField(
            model_name='course',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.studentregion'),
        ),
        migrations.AddField(
            model_name='session',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.studentregion'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.studentregion'),
        ),
        migrations.AddField(
            model_name='tutorname',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.studentregion'),
        ),
    ]
