# Generated by Django 5.0 on 2025-11-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0044_batches_created_at_batches_region_certificate_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='regions/'),
        ),
    ]
