# Generated by Django 5.0 on 2025-11-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0045_studentregion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregion',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
