# Generated by Django 5.0 on 2025-11-11 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0046_studentregion_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.session')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.tutorname')),
            ],
        ),
    ]
