# Generated by Django 5.0 on 2025-11-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0047_tutorattendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorattendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='tutorattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='tutorattendance',
            unique_together={('tutor', 'session', 'date')},
        ),
    ]
